ioc:
  bindings:
    - bind: "com.dp.creational.model.Media"
      to:
        - "com.dp.framework.prototype.Album"
        - "com.dp.framework.prototype.Picture"
        - "com.dp.framework.prototype.Song"
        - "com.dp.framework.prototype.Video"
    - bind: "com.dp.framework.model.PlayerMediaServer"
      to:
        - "com.dp.framework.singleton.MediaServer"
    - bind: "com.dp.framework.model.MediaPlayer"
      to:
        - "com.dp.framework.prototype.AlbumPlayer"
        - "com.dp.framework.prototype.PictureViewer"
        - "com.dp.framework.prototype.SongPlayer"
        - "com.dp.framework.prototype.VideoPlayer"
